namespace DVLD
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.pnSideBar = new SiticoneNetFrameworkUI.SiticonePanel();
            this.btnDrivers = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnApplications = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnAccountSettings = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnUsers = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnPeople = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnClose1 = new SiticoneNetFrameworkUI.SiticoneCloseButton();
            this.gbAccountSettings = new SiticoneNetFrameworkUI.SiticoneAuraGroupBox();
            this.btnSignOut = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnChangePassword = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnCurrentUserInfo = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.gbApplication = new SiticoneNetFrameworkUI.SiticoneAuraGroupBox();
            this.btnManageTestTypes = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnManageApplicationTypes = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnDetainLicenses = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnManageApplication = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnDrivingLicenseService = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.btnClose = new SiticoneNetFrameworkUI.SiticoneButtonAdvanced();
            this.pnSideBar.SuspendLayout();
            this.gbAccountSettings.SuspendLayout();
            this.gbApplication.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnSideBar
            // 
            this.pnSideBar.AcrylicTintColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.pnSideBar.BackColor = System.Drawing.Color.Transparent;
            this.pnSideBar.BorderAlignment = System.Drawing.Drawing2D.PenAlignment.Center;
            this.pnSideBar.BorderColor = System.Drawing.Color.Gray;
            this.pnSideBar.BorderDashPattern = null;
            this.pnSideBar.BorderGradientEndColor = System.Drawing.Color.FromArgb(((int)(((byte)(88)))), ((int)(((byte)(96)))), ((int)(((byte)(140)))));
            this.pnSideBar.BorderGradientStartColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(64)))), ((int)(((byte)(90)))));
            this.pnSideBar.BorderThickness = 2F;
            this.pnSideBar.Controls.Add(this.btnDrivers);
            this.pnSideBar.Controls.Add(this.btnApplications);
            this.pnSideBar.Controls.Add(this.btnAccountSettings);
            this.pnSideBar.Controls.Add(this.btnUsers);
            this.pnSideBar.Controls.Add(this.btnPeople);
            this.pnSideBar.CornerRadiusBottomLeft = 30F;
            this.pnSideBar.CornerRadiusBottomRight = 30F;
            this.pnSideBar.CornerRadiusTopLeft = 30F;
            this.pnSideBar.CornerRadiusTopRight = 30F;
            this.pnSideBar.Cursor = System.Windows.Forms.Cursors.Default;
            this.pnSideBar.EnableAcrylicEffect = false;
            this.pnSideBar.EnableMicaEffect = false;
            this.pnSideBar.EnableRippleEffect = false;
            this.pnSideBar.FillColor = System.Drawing.Color.DarkSlateBlue;
            this.pnSideBar.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.pnSideBar.ForeColor = System.Drawing.SystemColors.ControlText;
            this.pnSideBar.GradientColors = new System.Drawing.Color[] {
        System.Drawing.Color.White,
        System.Drawing.Color.LightGray,
        System.Drawing.Color.Gray};
            this.pnSideBar.GradientPositions = new float[] {
        0F,
        0.5F,
        1F};
            this.pnSideBar.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.pnSideBar.Location = new System.Drawing.Point(12, 12);
            this.pnSideBar.Name = "pnSideBar";
            this.pnSideBar.PatternColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.pnSideBar.PatternStyle = System.Drawing.Drawing2D.HatchStyle.LargeGrid;
            this.pnSideBar.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.pnSideBar.RippleAlpha = 50;
            this.pnSideBar.RippleAlphaDecrement = 3;
            this.pnSideBar.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.pnSideBar.RippleMaxSize = 600F;
            this.pnSideBar.RippleSpeed = 15F;
            this.pnSideBar.ShowBorder = true;
            this.pnSideBar.Size = new System.Drawing.Size(464, 821);
            this.pnSideBar.TabIndex = 0;
            this.pnSideBar.TabStop = true;
            this.pnSideBar.UseBorderGradient = true;
            this.pnSideBar.UseMultiGradient = false;
            this.pnSideBar.UsePatternTexture = false;
            this.pnSideBar.UseRadialGradient = false;
            // 
            // btnDrivers
            // 
            this.btnDrivers.BackColor = System.Drawing.Color.Transparent;
            this.btnDrivers.BadgeBackColor = System.Drawing.Color.Red;
            this.btnDrivers.BadgeForeColor = System.Drawing.Color.White;
            this.btnDrivers.BadgeRadius = 8;
            this.btnDrivers.BadgeRightMargin = 10;
            this.btnDrivers.BadgeValue = 0;
            this.btnDrivers.BorderColor = System.Drawing.Color.MediumSlateBlue;
            this.btnDrivers.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnDrivers.BorderColorStart = System.Drawing.Color.White;
            this.btnDrivers.BorderRadiusBottomLeft = 20;
            this.btnDrivers.BorderRadiusBottomRight = 20;
            this.btnDrivers.BorderRadiusTopLeft = 20;
            this.btnDrivers.BorderRadiusTopRight = 20;
            this.btnDrivers.BorderThickness = 1;
            this.btnDrivers.ButtonColorEnd = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(23)))), ((int)(((byte)(42)))));
            this.btnDrivers.ButtonColorStart = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(23)))), ((int)(((byte)(42)))));
            this.btnDrivers.ButtonImage = global::DVLD.Properties.Resources.Drivers_64;
            this.btnDrivers.CanBeep = false;
            this.btnDrivers.CanShake = false;
            this.btnDrivers.ClickSoundPath = null;
            this.btnDrivers.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnDrivers.DisabledOverlayOpacity = 0.5F;
            this.btnDrivers.EnableBorderGradient = false;
            this.btnDrivers.EnableClickSound = false;
            this.btnDrivers.EnableFocusBorder = false;
            this.btnDrivers.EnableHoverSound = false;
            this.btnDrivers.EnablePressScale = false;
            this.btnDrivers.EnableTextShadow = false;
            this.btnDrivers.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnDrivers.FocusBorderThickness = 2;
            this.btnDrivers.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDrivers.ForeColor = System.Drawing.Color.White;
            this.btnDrivers.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(41)))), ((int)(((byte)(30)))));
            this.btnDrivers.HoverSoundPath = null;
            this.btnDrivers.HoverTransitionSpeed = 0.08F;
            this.btnDrivers.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDrivers.ImageLeftMargin = 10;
            this.btnDrivers.ImageRightMargin = 0;
            this.btnDrivers.ImageSize = 30;
            this.btnDrivers.IsReadOnly = false;
            this.btnDrivers.Location = new System.Drawing.Point(77, 391);
            this.btnDrivers.MakeRadial = false;
            this.btnDrivers.Name = "btnDrivers";
            this.btnDrivers.PressAnimationSpeed = 0.2F;
            this.btnDrivers.PressDepth = 1;
            this.btnDrivers.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnDrivers.RippleExpandSpeedFactor = 0.05F;
            this.btnDrivers.RippleFadeSpeedFactor = 0.03F;
            this.btnDrivers.ShadowBlurFactor = 0.85F;
            this.btnDrivers.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnDrivers.ShadowOffsetX = 3;
            this.btnDrivers.ShadowOffsetY = 3;
            this.btnDrivers.Size = new System.Drawing.Size(315, 54);
            this.btnDrivers.TabIndex = 5;
            this.btnDrivers.Text = "Drivers";
            this.btnDrivers.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDrivers.TextPaddingBottom = 0;
            this.btnDrivers.TextPaddingLeft = 40;
            this.btnDrivers.TextPaddingRight = 0;
            this.btnDrivers.TextPaddingTop = 0;
            this.btnDrivers.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnDrivers.TextShadowOffsetX = 1;
            this.btnDrivers.TextShadowOffsetY = 1;
            this.btnDrivers.Click += new System.EventHandler(this.btnDrivers_Click);
            // 
            // btnApplications
            // 
            this.btnApplications.BackColor = System.Drawing.Color.Transparent;
            this.btnApplications.BadgeBackColor = System.Drawing.Color.Red;
            this.btnApplications.BadgeForeColor = System.Drawing.Color.White;
            this.btnApplications.BadgeRadius = 8;
            this.btnApplications.BadgeRightMargin = 10;
            this.btnApplications.BadgeValue = 0;
            this.btnApplications.BorderColor = System.Drawing.Color.MediumSlateBlue;
            this.btnApplications.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnApplications.BorderColorStart = System.Drawing.Color.White;
            this.btnApplications.BorderRadiusBottomLeft = 20;
            this.btnApplications.BorderRadiusBottomRight = 20;
            this.btnApplications.BorderRadiusTopLeft = 20;
            this.btnApplications.BorderRadiusTopRight = 20;
            this.btnApplications.BorderThickness = 1;
            this.btnApplications.ButtonColorEnd = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(23)))), ((int)(((byte)(42)))));
            this.btnApplications.ButtonColorStart = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(23)))), ((int)(((byte)(42)))));
            this.btnApplications.ButtonImage = global::DVLD.Properties.Resources.Applications_64;
            this.btnApplications.CanBeep = false;
            this.btnApplications.CanShake = false;
            this.btnApplications.ClickSoundPath = null;
            this.btnApplications.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnApplications.DisabledOverlayOpacity = 0.5F;
            this.btnApplications.EnableBorderGradient = false;
            this.btnApplications.EnableClickSound = false;
            this.btnApplications.EnableFocusBorder = false;
            this.btnApplications.EnableHoverSound = false;
            this.btnApplications.EnablePressScale = false;
            this.btnApplications.EnableTextShadow = false;
            this.btnApplications.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnApplications.FocusBorderThickness = 2;
            this.btnApplications.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnApplications.ForeColor = System.Drawing.Color.White;
            this.btnApplications.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(41)))), ((int)(((byte)(30)))));
            this.btnApplications.HoverSoundPath = null;
            this.btnApplications.HoverTransitionSpeed = 0.08F;
            this.btnApplications.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnApplications.ImageLeftMargin = 10;
            this.btnApplications.ImageRightMargin = 0;
            this.btnApplications.ImageSize = 30;
            this.btnApplications.IsReadOnly = false;
            this.btnApplications.Location = new System.Drawing.Point(77, 169);
            this.btnApplications.MakeRadial = false;
            this.btnApplications.Name = "btnApplications";
            this.btnApplications.PressAnimationSpeed = 0.2F;
            this.btnApplications.PressDepth = 1;
            this.btnApplications.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnApplications.RippleExpandSpeedFactor = 0.05F;
            this.btnApplications.RippleFadeSpeedFactor = 0.03F;
            this.btnApplications.ShadowBlurFactor = 0.85F;
            this.btnApplications.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnApplications.ShadowOffsetX = 3;
            this.btnApplications.ShadowOffsetY = 3;
            this.btnApplications.Size = new System.Drawing.Size(315, 54);
            this.btnApplications.TabIndex = 4;
            this.btnApplications.Text = "Applications";
            this.btnApplications.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnApplications.TextPaddingBottom = 0;
            this.btnApplications.TextPaddingLeft = 40;
            this.btnApplications.TextPaddingRight = 0;
            this.btnApplications.TextPaddingTop = 0;
            this.btnApplications.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnApplications.TextShadowOffsetX = 1;
            this.btnApplications.TextShadowOffsetY = 1;
            this.btnApplications.Click += new System.EventHandler(this.btnApplications_Click);
            // 
            // btnAccountSettings
            // 
            this.btnAccountSettings.BackColor = System.Drawing.Color.Transparent;
            this.btnAccountSettings.BadgeBackColor = System.Drawing.Color.Red;
            this.btnAccountSettings.BadgeForeColor = System.Drawing.Color.White;
            this.btnAccountSettings.BadgeRadius = 8;
            this.btnAccountSettings.BadgeRightMargin = 10;
            this.btnAccountSettings.BadgeValue = 0;
            this.btnAccountSettings.BorderColor = System.Drawing.Color.MediumSlateBlue;
            this.btnAccountSettings.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnAccountSettings.BorderColorStart = System.Drawing.Color.White;
            this.btnAccountSettings.BorderRadiusBottomLeft = 20;
            this.btnAccountSettings.BorderRadiusBottomRight = 20;
            this.btnAccountSettings.BorderRadiusTopLeft = 20;
            this.btnAccountSettings.BorderRadiusTopRight = 20;
            this.btnAccountSettings.BorderThickness = 1;
            this.btnAccountSettings.ButtonColorEnd = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(23)))), ((int)(((byte)(42)))));
            this.btnAccountSettings.ButtonColorStart = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(23)))), ((int)(((byte)(42)))));
            this.btnAccountSettings.ButtonImage = global::DVLD.Properties.Resources.account_settings_64;
            this.btnAccountSettings.CanBeep = false;
            this.btnAccountSettings.CanShake = false;
            this.btnAccountSettings.ClickSoundPath = null;
            this.btnAccountSettings.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnAccountSettings.DisabledOverlayOpacity = 0.5F;
            this.btnAccountSettings.EnableBorderGradient = false;
            this.btnAccountSettings.EnableClickSound = false;
            this.btnAccountSettings.EnableFocusBorder = false;
            this.btnAccountSettings.EnableHoverSound = false;
            this.btnAccountSettings.EnablePressScale = false;
            this.btnAccountSettings.EnableTextShadow = false;
            this.btnAccountSettings.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnAccountSettings.FocusBorderThickness = 2;
            this.btnAccountSettings.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAccountSettings.ForeColor = System.Drawing.Color.White;
            this.btnAccountSettings.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(41)))), ((int)(((byte)(30)))));
            this.btnAccountSettings.HoverSoundPath = null;
            this.btnAccountSettings.HoverTransitionSpeed = 0.08F;
            this.btnAccountSettings.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAccountSettings.ImageLeftMargin = 10;
            this.btnAccountSettings.ImageRightMargin = 0;
            this.btnAccountSettings.ImageSize = 30;
            this.btnAccountSettings.IsReadOnly = false;
            this.btnAccountSettings.Location = new System.Drawing.Point(77, 613);
            this.btnAccountSettings.MakeRadial = false;
            this.btnAccountSettings.Name = "btnAccountSettings";
            this.btnAccountSettings.PressAnimationSpeed = 0.2F;
            this.btnAccountSettings.PressDepth = 1;
            this.btnAccountSettings.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnAccountSettings.RippleExpandSpeedFactor = 0.05F;
            this.btnAccountSettings.RippleFadeSpeedFactor = 0.03F;
            this.btnAccountSettings.ShadowBlurFactor = 0.85F;
            this.btnAccountSettings.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnAccountSettings.ShadowOffsetX = 3;
            this.btnAccountSettings.ShadowOffsetY = 3;
            this.btnAccountSettings.Size = new System.Drawing.Size(315, 54);
            this.btnAccountSettings.TabIndex = 3;
            this.btnAccountSettings.Text = "Account Settings";
            this.btnAccountSettings.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAccountSettings.TextPaddingBottom = 0;
            this.btnAccountSettings.TextPaddingLeft = 40;
            this.btnAccountSettings.TextPaddingRight = 0;
            this.btnAccountSettings.TextPaddingTop = 0;
            this.btnAccountSettings.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnAccountSettings.TextShadowOffsetX = 1;
            this.btnAccountSettings.TextShadowOffsetY = 1;
            this.btnAccountSettings.Click += new System.EventHandler(this.btnAccountSettings_Click);
            // 
            // btnUsers
            // 
            this.btnUsers.BackColor = System.Drawing.Color.Transparent;
            this.btnUsers.BadgeBackColor = System.Drawing.Color.Red;
            this.btnUsers.BadgeForeColor = System.Drawing.Color.White;
            this.btnUsers.BadgeRadius = 8;
            this.btnUsers.BadgeRightMargin = 10;
            this.btnUsers.BadgeValue = 0;
            this.btnUsers.BorderColor = System.Drawing.Color.MediumSlateBlue;
            this.btnUsers.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnUsers.BorderColorStart = System.Drawing.Color.White;
            this.btnUsers.BorderRadiusBottomLeft = 20;
            this.btnUsers.BorderRadiusBottomRight = 20;
            this.btnUsers.BorderRadiusTopLeft = 20;
            this.btnUsers.BorderRadiusTopRight = 20;
            this.btnUsers.BorderThickness = 1;
            this.btnUsers.ButtonColorEnd = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(23)))), ((int)(((byte)(42)))));
            this.btnUsers.ButtonColorStart = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(23)))), ((int)(((byte)(42)))));
            this.btnUsers.ButtonImage = global::DVLD.Properties.Resources.Users_2_64;
            this.btnUsers.CanBeep = false;
            this.btnUsers.CanShake = false;
            this.btnUsers.ClickSoundPath = null;
            this.btnUsers.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnUsers.DisabledOverlayOpacity = 0.5F;
            this.btnUsers.EnableBorderGradient = false;
            this.btnUsers.EnableClickSound = false;
            this.btnUsers.EnableFocusBorder = false;
            this.btnUsers.EnableHoverSound = false;
            this.btnUsers.EnablePressScale = false;
            this.btnUsers.EnableTextShadow = false;
            this.btnUsers.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnUsers.FocusBorderThickness = 2;
            this.btnUsers.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUsers.ForeColor = System.Drawing.Color.White;
            this.btnUsers.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(41)))), ((int)(((byte)(30)))));
            this.btnUsers.HoverSoundPath = null;
            this.btnUsers.HoverTransitionSpeed = 0.08F;
            this.btnUsers.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUsers.ImageLeftMargin = 10;
            this.btnUsers.ImageRightMargin = 0;
            this.btnUsers.ImageSize = 30;
            this.btnUsers.IsReadOnly = false;
            this.btnUsers.Location = new System.Drawing.Point(77, 502);
            this.btnUsers.MakeRadial = false;
            this.btnUsers.Name = "btnUsers";
            this.btnUsers.PressAnimationSpeed = 0.2F;
            this.btnUsers.PressDepth = 1;
            this.btnUsers.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnUsers.RippleExpandSpeedFactor = 0.05F;
            this.btnUsers.RippleFadeSpeedFactor = 0.03F;
            this.btnUsers.ShadowBlurFactor = 0.85F;
            this.btnUsers.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnUsers.ShadowOffsetX = 3;
            this.btnUsers.ShadowOffsetY = 3;
            this.btnUsers.Size = new System.Drawing.Size(315, 54);
            this.btnUsers.TabIndex = 2;
            this.btnUsers.Text = "Users";
            this.btnUsers.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUsers.TextPaddingBottom = 0;
            this.btnUsers.TextPaddingLeft = 40;
            this.btnUsers.TextPaddingRight = 0;
            this.btnUsers.TextPaddingTop = 0;
            this.btnUsers.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnUsers.TextShadowOffsetX = 1;
            this.btnUsers.TextShadowOffsetY = 1;
            this.btnUsers.Click += new System.EventHandler(this.btnUsers_Click);
            // 
            // btnPeople
            // 
            this.btnPeople.BackColor = System.Drawing.Color.Transparent;
            this.btnPeople.BadgeBackColor = System.Drawing.Color.Red;
            this.btnPeople.BadgeForeColor = System.Drawing.Color.White;
            this.btnPeople.BadgeRadius = 8;
            this.btnPeople.BadgeRightMargin = 10;
            this.btnPeople.BadgeValue = 0;
            this.btnPeople.BorderColor = System.Drawing.Color.MediumSlateBlue;
            this.btnPeople.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnPeople.BorderColorStart = System.Drawing.Color.White;
            this.btnPeople.BorderRadiusBottomLeft = 20;
            this.btnPeople.BorderRadiusBottomRight = 20;
            this.btnPeople.BorderRadiusTopLeft = 20;
            this.btnPeople.BorderRadiusTopRight = 20;
            this.btnPeople.BorderThickness = 1;
            this.btnPeople.ButtonColorEnd = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(23)))), ((int)(((byte)(42)))));
            this.btnPeople.ButtonColorStart = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(23)))), ((int)(((byte)(42)))));
            this.btnPeople.ButtonImage = global::DVLD.Properties.Resources.People_64;
            this.btnPeople.CanBeep = false;
            this.btnPeople.CanShake = false;
            this.btnPeople.ClickSoundPath = null;
            this.btnPeople.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnPeople.DisabledOverlayOpacity = 0.5F;
            this.btnPeople.EnableBorderGradient = false;
            this.btnPeople.EnableClickSound = false;
            this.btnPeople.EnableFocusBorder = false;
            this.btnPeople.EnableHoverSound = false;
            this.btnPeople.EnablePressScale = false;
            this.btnPeople.EnableTextShadow = false;
            this.btnPeople.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnPeople.FocusBorderThickness = 2;
            this.btnPeople.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPeople.ForeColor = System.Drawing.Color.White;
            this.btnPeople.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(41)))), ((int)(((byte)(30)))));
            this.btnPeople.HoverSoundPath = null;
            this.btnPeople.HoverTransitionSpeed = 0.08F;
            this.btnPeople.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPeople.ImageLeftMargin = 10;
            this.btnPeople.ImageRightMargin = 0;
            this.btnPeople.ImageSize = 30;
            this.btnPeople.IsReadOnly = false;
            this.btnPeople.Location = new System.Drawing.Point(77, 280);
            this.btnPeople.MakeRadial = false;
            this.btnPeople.Name = "btnPeople";
            this.btnPeople.PressAnimationSpeed = 0.2F;
            this.btnPeople.PressDepth = 1;
            this.btnPeople.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnPeople.RippleExpandSpeedFactor = 0.05F;
            this.btnPeople.RippleFadeSpeedFactor = 0.03F;
            this.btnPeople.ShadowBlurFactor = 0.85F;
            this.btnPeople.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnPeople.ShadowOffsetX = 3;
            this.btnPeople.ShadowOffsetY = 3;
            this.btnPeople.Size = new System.Drawing.Size(315, 54);
            this.btnPeople.TabIndex = 1;
            this.btnPeople.Text = "People";
            this.btnPeople.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPeople.TextPaddingBottom = 0;
            this.btnPeople.TextPaddingLeft = 40;
            this.btnPeople.TextPaddingRight = 0;
            this.btnPeople.TextPaddingTop = 0;
            this.btnPeople.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnPeople.TextShadowOffsetX = 1;
            this.btnPeople.TextShadowOffsetY = 1;
            this.btnPeople.Click += new System.EventHandler(this.btnPeople_Click);
            // 
            // btnClose1
            // 
            this.btnClose1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btnClose1.CountdownFont = new System.Drawing.Font("Segoe UI", 9F);
            this.btnClose1.IconSize = 12;
            this.btnClose1.IconThickness = 3;
            this.btnClose1.Location = new System.Drawing.Point(1493, 12);
            this.btnClose1.Name = "btnClose1";
            this.btnClose1.Size = new System.Drawing.Size(38, 38);
            this.btnClose1.TabIndex = 1;
            this.btnClose1.Text = "siticoneCloseButton1";
            this.btnClose1.TooltipText = "Close button";
            // 
            // gbAccountSettings
            // 
            this.gbAccountSettings.AccentLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(122)))), ((int)(((byte)(204)))));
            this.gbAccountSettings.BackColor = System.Drawing.Color.Transparent;
            this.gbAccountSettings.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(201)))), ((int)(((byte)(207)))), ((int)(((byte)(216)))));
            this.gbAccountSettings.BorderRadius = 15;
            this.gbAccountSettings.Controls.Add(this.btnSignOut);
            this.gbAccountSettings.Controls.Add(this.btnChangePassword);
            this.gbAccountSettings.Controls.Add(this.btnCurrentUserInfo);
            this.gbAccountSettings.FillColor = System.Drawing.Color.White;
            this.gbAccountSettings.Font = new System.Drawing.Font("Segoe UI Black", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbAccountSettings.HeaderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(242)))), ((int)(((byte)(245)))));
            this.gbAccountSettings.HeaderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(228)))), ((int)(((byte)(233)))));
            this.gbAccountSettings.Location = new System.Drawing.Point(682, 155);
            this.gbAccountSettings.Name = "gbAccountSettings";
            this.gbAccountSettings.Padding = new System.Windows.Forms.Padding(8, 40, 8, 8);
            this.gbAccountSettings.Size = new System.Drawing.Size(707, 331);
            this.gbAccountSettings.TabIndex = 2;
            this.gbAccountSettings.Text = "Account Settings";
            this.gbAccountSettings.TitleFont = new System.Drawing.Font("Segoe UI Black", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbAccountSettings.TitleTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(65)))), ((int)(((byte)(81)))));
            this.gbAccountSettings.Visible = false;
            // 
            // btnSignOut
            // 
            this.btnSignOut.BackColor = System.Drawing.Color.Transparent;
            this.btnSignOut.BadgeBackColor = System.Drawing.Color.Red;
            this.btnSignOut.BadgeForeColor = System.Drawing.Color.White;
            this.btnSignOut.BadgeRadius = 8;
            this.btnSignOut.BadgeRightMargin = 10;
            this.btnSignOut.BadgeValue = 0;
            this.btnSignOut.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(165)))), ((int)(((byte)(165)))));
            this.btnSignOut.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnSignOut.BorderColorStart = System.Drawing.Color.White;
            this.btnSignOut.BorderRadiusBottomLeft = 20;
            this.btnSignOut.BorderRadiusBottomRight = 20;
            this.btnSignOut.BorderRadiusTopLeft = 20;
            this.btnSignOut.BorderRadiusTopRight = 20;
            this.btnSignOut.BorderThickness = 1;
            this.btnSignOut.ButtonColorEnd = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.btnSignOut.ButtonColorStart = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.btnSignOut.ButtonImage = global::DVLD.Properties.Resources.sign_out_32__2;
            this.btnSignOut.CanBeep = false;
            this.btnSignOut.CanShake = false;
            this.btnSignOut.ClickSoundPath = null;
            this.btnSignOut.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnSignOut.DisabledOverlayOpacity = 0.5F;
            this.btnSignOut.EnableBorderGradient = false;
            this.btnSignOut.EnableClickSound = false;
            this.btnSignOut.EnableFocusBorder = false;
            this.btnSignOut.EnableHoverSound = false;
            this.btnSignOut.EnablePressScale = false;
            this.btnSignOut.EnableTextShadow = false;
            this.btnSignOut.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSignOut.FocusBorderThickness = 2;
            this.btnSignOut.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSignOut.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.btnSignOut.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(202)))), ((int)(((byte)(202)))));
            this.btnSignOut.HoverSoundPath = null;
            this.btnSignOut.HoverTransitionSpeed = 0.08F;
            this.btnSignOut.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSignOut.ImageLeftMargin = 10;
            this.btnSignOut.ImageRightMargin = 0;
            this.btnSignOut.ImageSize = 35;
            this.btnSignOut.IsReadOnly = false;
            this.btnSignOut.Location = new System.Drawing.Point(239, 222);
            this.btnSignOut.MakeRadial = false;
            this.btnSignOut.Name = "btnSignOut";
            this.btnSignOut.PressAnimationSpeed = 0.2F;
            this.btnSignOut.PressDepth = 1;
            this.btnSignOut.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnSignOut.RippleExpandSpeedFactor = 0.05F;
            this.btnSignOut.RippleFadeSpeedFactor = 0.03F;
            this.btnSignOut.ShadowBlurFactor = 0.85F;
            this.btnSignOut.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnSignOut.ShadowOffsetX = 3;
            this.btnSignOut.ShadowOffsetY = 3;
            this.btnSignOut.Size = new System.Drawing.Size(315, 54);
            this.btnSignOut.TabIndex = 6;
            this.btnSignOut.Text = "Sign Out";
            this.btnSignOut.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSignOut.TextPaddingBottom = 0;
            this.btnSignOut.TextPaddingLeft = 40;
            this.btnSignOut.TextPaddingRight = 0;
            this.btnSignOut.TextPaddingTop = 0;
            this.btnSignOut.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnSignOut.TextShadowOffsetX = 1;
            this.btnSignOut.TextShadowOffsetY = 1;
            this.btnSignOut.Click += new System.EventHandler(this.btnSignOut_Click);
            // 
            // btnChangePassword
            // 
            this.btnChangePassword.BackColor = System.Drawing.Color.Transparent;
            this.btnChangePassword.BadgeBackColor = System.Drawing.Color.Red;
            this.btnChangePassword.BadgeForeColor = System.Drawing.Color.White;
            this.btnChangePassword.BadgeRadius = 8;
            this.btnChangePassword.BadgeRightMargin = 10;
            this.btnChangePassword.BadgeValue = 0;
            this.btnChangePassword.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(130)))), ((int)(((byte)(246)))));
            this.btnChangePassword.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnChangePassword.BorderColorStart = System.Drawing.Color.White;
            this.btnChangePassword.BorderRadiusBottomLeft = 20;
            this.btnChangePassword.BorderRadiusBottomRight = 20;
            this.btnChangePassword.BorderRadiusTopLeft = 20;
            this.btnChangePassword.BorderRadiusTopRight = 20;
            this.btnChangePassword.BorderThickness = 1;
            this.btnChangePassword.ButtonColorEnd = System.Drawing.Color.White;
            this.btnChangePassword.ButtonColorStart = System.Drawing.Color.White;
            this.btnChangePassword.ButtonImage = global::DVLD.Properties.Resources.Password_32;
            this.btnChangePassword.CanBeep = false;
            this.btnChangePassword.CanShake = false;
            this.btnChangePassword.ClickSoundPath = null;
            this.btnChangePassword.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnChangePassword.DisabledOverlayOpacity = 0.5F;
            this.btnChangePassword.EnableBorderGradient = false;
            this.btnChangePassword.EnableClickSound = false;
            this.btnChangePassword.EnableFocusBorder = false;
            this.btnChangePassword.EnableHoverSound = false;
            this.btnChangePassword.EnablePressScale = false;
            this.btnChangePassword.EnableTextShadow = false;
            this.btnChangePassword.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnChangePassword.FocusBorderThickness = 2;
            this.btnChangePassword.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChangePassword.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.btnChangePassword.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(246)))), ((int)(((byte)(255)))));
            this.btnChangePassword.HoverSoundPath = null;
            this.btnChangePassword.HoverTransitionSpeed = 0.08F;
            this.btnChangePassword.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChangePassword.ImageLeftMargin = 10;
            this.btnChangePassword.ImageRightMargin = 0;
            this.btnChangePassword.ImageSize = 35;
            this.btnChangePassword.IsReadOnly = false;
            this.btnChangePassword.Location = new System.Drawing.Point(381, 111);
            this.btnChangePassword.MakeRadial = false;
            this.btnChangePassword.Name = "btnChangePassword";
            this.btnChangePassword.PressAnimationSpeed = 0.2F;
            this.btnChangePassword.PressDepth = 1;
            this.btnChangePassword.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnChangePassword.RippleExpandSpeedFactor = 0.05F;
            this.btnChangePassword.RippleFadeSpeedFactor = 0.03F;
            this.btnChangePassword.ShadowBlurFactor = 0.85F;
            this.btnChangePassword.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnChangePassword.ShadowOffsetX = 3;
            this.btnChangePassword.ShadowOffsetY = 3;
            this.btnChangePassword.Size = new System.Drawing.Size(315, 54);
            this.btnChangePassword.TabIndex = 5;
            this.btnChangePassword.Text = "Change Password";
            this.btnChangePassword.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChangePassword.TextPaddingBottom = 0;
            this.btnChangePassword.TextPaddingLeft = 40;
            this.btnChangePassword.TextPaddingRight = 0;
            this.btnChangePassword.TextPaddingTop = 0;
            this.btnChangePassword.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnChangePassword.TextShadowOffsetX = 1;
            this.btnChangePassword.TextShadowOffsetY = 1;
            this.btnChangePassword.Click += new System.EventHandler(this.btnChangePassword_Click);
            // 
            // btnCurrentUserInfo
            // 
            this.btnCurrentUserInfo.BackColor = System.Drawing.Color.Transparent;
            this.btnCurrentUserInfo.BadgeBackColor = System.Drawing.Color.Red;
            this.btnCurrentUserInfo.BadgeForeColor = System.Drawing.Color.White;
            this.btnCurrentUserInfo.BadgeRadius = 8;
            this.btnCurrentUserInfo.BadgeRightMargin = 10;
            this.btnCurrentUserInfo.BadgeValue = 0;
            this.btnCurrentUserInfo.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(130)))), ((int)(((byte)(246)))));
            this.btnCurrentUserInfo.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnCurrentUserInfo.BorderColorStart = System.Drawing.Color.White;
            this.btnCurrentUserInfo.BorderRadiusBottomLeft = 20;
            this.btnCurrentUserInfo.BorderRadiusBottomRight = 20;
            this.btnCurrentUserInfo.BorderRadiusTopLeft = 20;
            this.btnCurrentUserInfo.BorderRadiusTopRight = 20;
            this.btnCurrentUserInfo.BorderThickness = 1;
            this.btnCurrentUserInfo.ButtonColorEnd = System.Drawing.Color.White;
            this.btnCurrentUserInfo.ButtonColorStart = System.Drawing.Color.White;
            this.btnCurrentUserInfo.ButtonImage = global::DVLD.Properties.Resources.PersonDetails_32;
            this.btnCurrentUserInfo.CanBeep = false;
            this.btnCurrentUserInfo.CanShake = false;
            this.btnCurrentUserInfo.ClickSoundPath = null;
            this.btnCurrentUserInfo.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnCurrentUserInfo.DisabledOverlayOpacity = 0.5F;
            this.btnCurrentUserInfo.EnableBorderGradient = false;
            this.btnCurrentUserInfo.EnableClickSound = false;
            this.btnCurrentUserInfo.EnableFocusBorder = false;
            this.btnCurrentUserInfo.EnableHoverSound = false;
            this.btnCurrentUserInfo.EnablePressScale = false;
            this.btnCurrentUserInfo.EnableTextShadow = false;
            this.btnCurrentUserInfo.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCurrentUserInfo.FocusBorderThickness = 2;
            this.btnCurrentUserInfo.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCurrentUserInfo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.btnCurrentUserInfo.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(246)))), ((int)(((byte)(255)))));
            this.btnCurrentUserInfo.HoverSoundPath = null;
            this.btnCurrentUserInfo.HoverTransitionSpeed = 0.08F;
            this.btnCurrentUserInfo.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCurrentUserInfo.ImageLeftMargin = 10;
            this.btnCurrentUserInfo.ImageRightMargin = 0;
            this.btnCurrentUserInfo.ImageSize = 35;
            this.btnCurrentUserInfo.IsReadOnly = false;
            this.btnCurrentUserInfo.Location = new System.Drawing.Point(11, 111);
            this.btnCurrentUserInfo.MakeRadial = false;
            this.btnCurrentUserInfo.Name = "btnCurrentUserInfo";
            this.btnCurrentUserInfo.PressAnimationSpeed = 0.2F;
            this.btnCurrentUserInfo.PressDepth = 1;
            this.btnCurrentUserInfo.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnCurrentUserInfo.RippleExpandSpeedFactor = 0.05F;
            this.btnCurrentUserInfo.RippleFadeSpeedFactor = 0.03F;
            this.btnCurrentUserInfo.ShadowBlurFactor = 0.85F;
            this.btnCurrentUserInfo.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnCurrentUserInfo.ShadowOffsetX = 3;
            this.btnCurrentUserInfo.ShadowOffsetY = 3;
            this.btnCurrentUserInfo.Size = new System.Drawing.Size(315, 54);
            this.btnCurrentUserInfo.TabIndex = 4;
            this.btnCurrentUserInfo.Text = "Current User Info";
            this.btnCurrentUserInfo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCurrentUserInfo.TextPaddingBottom = 0;
            this.btnCurrentUserInfo.TextPaddingLeft = 40;
            this.btnCurrentUserInfo.TextPaddingRight = 0;
            this.btnCurrentUserInfo.TextPaddingTop = 0;
            this.btnCurrentUserInfo.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnCurrentUserInfo.TextShadowOffsetX = 1;
            this.btnCurrentUserInfo.TextShadowOffsetY = 1;
            this.btnCurrentUserInfo.Click += new System.EventHandler(this.btnCurrentUserInfo_Click);
            // 
            // gbApplication
            // 
            this.gbApplication.AccentLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(122)))), ((int)(((byte)(204)))));
            this.gbApplication.BackColor = System.Drawing.Color.Transparent;
            this.gbApplication.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(201)))), ((int)(((byte)(207)))), ((int)(((byte)(216)))));
            this.gbApplication.BorderRadius = 15;
            this.gbApplication.Controls.Add(this.btnManageTestTypes);
            this.gbApplication.Controls.Add(this.btnManageApplicationTypes);
            this.gbApplication.Controls.Add(this.btnDetainLicenses);
            this.gbApplication.Controls.Add(this.btnManageApplication);
            this.gbApplication.Controls.Add(this.btnDrivingLicenseService);
            this.gbApplication.FillColor = System.Drawing.Color.White;
            this.gbApplication.Font = new System.Drawing.Font("Segoe UI Black", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbApplication.HeaderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(242)))), ((int)(((byte)(245)))));
            this.gbApplication.HeaderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(228)))), ((int)(((byte)(233)))));
            this.gbApplication.Location = new System.Drawing.Point(543, 124);
            this.gbApplication.Name = "gbApplication";
            this.gbApplication.Padding = new System.Windows.Forms.Padding(8, 40, 8, 8);
            this.gbApplication.Size = new System.Drawing.Size(892, 431);
            this.gbApplication.TabIndex = 7;
            this.gbApplication.Text = "Applications";
            this.gbApplication.TitleFont = new System.Drawing.Font("Segoe UI Black", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbApplication.TitleTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(65)))), ((int)(((byte)(81)))));
            this.gbApplication.Visible = false;
            // 
            // btnManageTestTypes
            // 
            this.btnManageTestTypes.BackColor = System.Drawing.Color.Transparent;
            this.btnManageTestTypes.BadgeBackColor = System.Drawing.Color.Red;
            this.btnManageTestTypes.BadgeForeColor = System.Drawing.Color.White;
            this.btnManageTestTypes.BadgeRadius = 8;
            this.btnManageTestTypes.BadgeRightMargin = 10;
            this.btnManageTestTypes.BadgeValue = 0;
            this.btnManageTestTypes.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(130)))), ((int)(((byte)(246)))));
            this.btnManageTestTypes.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnManageTestTypes.BorderColorStart = System.Drawing.Color.White;
            this.btnManageTestTypes.BorderRadiusBottomLeft = 20;
            this.btnManageTestTypes.BorderRadiusBottomRight = 20;
            this.btnManageTestTypes.BorderRadiusTopLeft = 20;
            this.btnManageTestTypes.BorderRadiusTopRight = 20;
            this.btnManageTestTypes.BorderThickness = 1;
            this.btnManageTestTypes.ButtonColorEnd = System.Drawing.Color.White;
            this.btnManageTestTypes.ButtonColorStart = System.Drawing.Color.White;
            this.btnManageTestTypes.ButtonImage = global::DVLD.Properties.Resources.TestType_32;
            this.btnManageTestTypes.CanBeep = false;
            this.btnManageTestTypes.CanShake = false;
            this.btnManageTestTypes.ClickSoundPath = null;
            this.btnManageTestTypes.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnManageTestTypes.DisabledOverlayOpacity = 0.5F;
            this.btnManageTestTypes.EnableBorderGradient = false;
            this.btnManageTestTypes.EnableClickSound = false;
            this.btnManageTestTypes.EnableFocusBorder = false;
            this.btnManageTestTypes.EnableHoverSound = false;
            this.btnManageTestTypes.EnablePressScale = false;
            this.btnManageTestTypes.EnableTextShadow = false;
            this.btnManageTestTypes.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnManageTestTypes.FocusBorderThickness = 2;
            this.btnManageTestTypes.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnManageTestTypes.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.btnManageTestTypes.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(246)))), ((int)(((byte)(255)))));
            this.btnManageTestTypes.HoverSoundPath = null;
            this.btnManageTestTypes.HoverTransitionSpeed = 0.08F;
            this.btnManageTestTypes.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManageTestTypes.ImageLeftMargin = 10;
            this.btnManageTestTypes.ImageRightMargin = 0;
            this.btnManageTestTypes.ImageSize = 35;
            this.btnManageTestTypes.IsReadOnly = false;
            this.btnManageTestTypes.Location = new System.Drawing.Point(268, 342);
            this.btnManageTestTypes.MakeRadial = false;
            this.btnManageTestTypes.Name = "btnManageTestTypes";
            this.btnManageTestTypes.PressAnimationSpeed = 0.2F;
            this.btnManageTestTypes.PressDepth = 1;
            this.btnManageTestTypes.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnManageTestTypes.RippleExpandSpeedFactor = 0.05F;
            this.btnManageTestTypes.RippleFadeSpeedFactor = 0.03F;
            this.btnManageTestTypes.ShadowBlurFactor = 0.85F;
            this.btnManageTestTypes.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnManageTestTypes.ShadowOffsetX = 3;
            this.btnManageTestTypes.ShadowOffsetY = 3;
            this.btnManageTestTypes.Size = new System.Drawing.Size(361, 54);
            this.btnManageTestTypes.TabIndex = 7;
            this.btnManageTestTypes.Text = "Manage Test Types";
            this.btnManageTestTypes.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageTestTypes.TextPaddingBottom = 0;
            this.btnManageTestTypes.TextPaddingLeft = 40;
            this.btnManageTestTypes.TextPaddingRight = 0;
            this.btnManageTestTypes.TextPaddingTop = 0;
            this.btnManageTestTypes.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnManageTestTypes.TextShadowOffsetX = 1;
            this.btnManageTestTypes.TextShadowOffsetY = 1;
            this.btnManageTestTypes.Click += new System.EventHandler(this.btnManageTestTypes_Click);
            // 
            // btnManageApplicationTypes
            // 
            this.btnManageApplicationTypes.BackColor = System.Drawing.Color.Transparent;
            this.btnManageApplicationTypes.BadgeBackColor = System.Drawing.Color.Red;
            this.btnManageApplicationTypes.BadgeForeColor = System.Drawing.Color.White;
            this.btnManageApplicationTypes.BadgeRadius = 8;
            this.btnManageApplicationTypes.BadgeRightMargin = 10;
            this.btnManageApplicationTypes.BadgeValue = 0;
            this.btnManageApplicationTypes.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(130)))), ((int)(((byte)(246)))));
            this.btnManageApplicationTypes.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnManageApplicationTypes.BorderColorStart = System.Drawing.Color.White;
            this.btnManageApplicationTypes.BorderRadiusBottomLeft = 20;
            this.btnManageApplicationTypes.BorderRadiusBottomRight = 20;
            this.btnManageApplicationTypes.BorderRadiusTopLeft = 20;
            this.btnManageApplicationTypes.BorderRadiusTopRight = 20;
            this.btnManageApplicationTypes.BorderThickness = 1;
            this.btnManageApplicationTypes.ButtonColorEnd = System.Drawing.Color.White;
            this.btnManageApplicationTypes.ButtonColorStart = System.Drawing.Color.White;
            this.btnManageApplicationTypes.ButtonImage = global::DVLD.Properties.Resources.Application_Types_64;
            this.btnManageApplicationTypes.CanBeep = false;
            this.btnManageApplicationTypes.CanShake = false;
            this.btnManageApplicationTypes.ClickSoundPath = null;
            this.btnManageApplicationTypes.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnManageApplicationTypes.DisabledOverlayOpacity = 0.5F;
            this.btnManageApplicationTypes.EnableBorderGradient = false;
            this.btnManageApplicationTypes.EnableClickSound = false;
            this.btnManageApplicationTypes.EnableFocusBorder = false;
            this.btnManageApplicationTypes.EnableHoverSound = false;
            this.btnManageApplicationTypes.EnablePressScale = false;
            this.btnManageApplicationTypes.EnableTextShadow = false;
            this.btnManageApplicationTypes.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnManageApplicationTypes.FocusBorderThickness = 2;
            this.btnManageApplicationTypes.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnManageApplicationTypes.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.btnManageApplicationTypes.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(246)))), ((int)(((byte)(255)))));
            this.btnManageApplicationTypes.HoverSoundPath = null;
            this.btnManageApplicationTypes.HoverTransitionSpeed = 0.08F;
            this.btnManageApplicationTypes.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManageApplicationTypes.ImageLeftMargin = 10;
            this.btnManageApplicationTypes.ImageRightMargin = 0;
            this.btnManageApplicationTypes.ImageSize = 35;
            this.btnManageApplicationTypes.IsReadOnly = false;
            this.btnManageApplicationTypes.Location = new System.Drawing.Point(520, 237);
            this.btnManageApplicationTypes.MakeRadial = false;
            this.btnManageApplicationTypes.Name = "btnManageApplicationTypes";
            this.btnManageApplicationTypes.PressAnimationSpeed = 0.2F;
            this.btnManageApplicationTypes.PressDepth = 1;
            this.btnManageApplicationTypes.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnManageApplicationTypes.RippleExpandSpeedFactor = 0.05F;
            this.btnManageApplicationTypes.RippleFadeSpeedFactor = 0.03F;
            this.btnManageApplicationTypes.ShadowBlurFactor = 0.85F;
            this.btnManageApplicationTypes.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnManageApplicationTypes.ShadowOffsetX = 3;
            this.btnManageApplicationTypes.ShadowOffsetY = 3;
            this.btnManageApplicationTypes.Size = new System.Drawing.Size(361, 54);
            this.btnManageApplicationTypes.TabIndex = 8;
            this.btnManageApplicationTypes.Text = "Manage Application Types";
            this.btnManageApplicationTypes.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageApplicationTypes.TextPaddingBottom = 0;
            this.btnManageApplicationTypes.TextPaddingLeft = 40;
            this.btnManageApplicationTypes.TextPaddingRight = 0;
            this.btnManageApplicationTypes.TextPaddingTop = 0;
            this.btnManageApplicationTypes.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnManageApplicationTypes.TextShadowOffsetX = 1;
            this.btnManageApplicationTypes.TextShadowOffsetY = 1;
            this.btnManageApplicationTypes.Click += new System.EventHandler(this.btnManageApplicationTypes_Click);
            // 
            // btnDetainLicenses
            // 
            this.btnDetainLicenses.BackColor = System.Drawing.Color.Transparent;
            this.btnDetainLicenses.BadgeBackColor = System.Drawing.Color.Red;
            this.btnDetainLicenses.BadgeForeColor = System.Drawing.Color.White;
            this.btnDetainLicenses.BadgeRadius = 8;
            this.btnDetainLicenses.BadgeRightMargin = 10;
            this.btnDetainLicenses.BadgeValue = 0;
            this.btnDetainLicenses.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(130)))), ((int)(((byte)(246)))));
            this.btnDetainLicenses.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnDetainLicenses.BorderColorStart = System.Drawing.Color.White;
            this.btnDetainLicenses.BorderRadiusBottomLeft = 20;
            this.btnDetainLicenses.BorderRadiusBottomRight = 20;
            this.btnDetainLicenses.BorderRadiusTopLeft = 20;
            this.btnDetainLicenses.BorderRadiusTopRight = 20;
            this.btnDetainLicenses.BorderThickness = 1;
            this.btnDetainLicenses.ButtonColorEnd = System.Drawing.Color.White;
            this.btnDetainLicenses.ButtonColorStart = System.Drawing.Color.White;
            this.btnDetainLicenses.ButtonImage = global::DVLD.Properties.Resources.Detain_32;
            this.btnDetainLicenses.CanBeep = false;
            this.btnDetainLicenses.CanShake = false;
            this.btnDetainLicenses.ClickSoundPath = null;
            this.btnDetainLicenses.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnDetainLicenses.DisabledOverlayOpacity = 0.5F;
            this.btnDetainLicenses.EnableBorderGradient = false;
            this.btnDetainLicenses.EnableClickSound = false;
            this.btnDetainLicenses.EnableFocusBorder = false;
            this.btnDetainLicenses.EnableHoverSound = false;
            this.btnDetainLicenses.EnablePressScale = false;
            this.btnDetainLicenses.EnableTextShadow = false;
            this.btnDetainLicenses.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnDetainLicenses.FocusBorderThickness = 2;
            this.btnDetainLicenses.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDetainLicenses.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.btnDetainLicenses.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(246)))), ((int)(((byte)(255)))));
            this.btnDetainLicenses.HoverSoundPath = null;
            this.btnDetainLicenses.HoverTransitionSpeed = 0.08F;
            this.btnDetainLicenses.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDetainLicenses.ImageLeftMargin = 10;
            this.btnDetainLicenses.ImageRightMargin = 0;
            this.btnDetainLicenses.ImageSize = 35;
            this.btnDetainLicenses.IsReadOnly = false;
            this.btnDetainLicenses.Location = new System.Drawing.Point(11, 237);
            this.btnDetainLicenses.MakeRadial = false;
            this.btnDetainLicenses.Name = "btnDetainLicenses";
            this.btnDetainLicenses.PressAnimationSpeed = 0.2F;
            this.btnDetainLicenses.PressDepth = 1;
            this.btnDetainLicenses.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnDetainLicenses.RippleExpandSpeedFactor = 0.05F;
            this.btnDetainLicenses.RippleFadeSpeedFactor = 0.03F;
            this.btnDetainLicenses.ShadowBlurFactor = 0.85F;
            this.btnDetainLicenses.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnDetainLicenses.ShadowOffsetX = 3;
            this.btnDetainLicenses.ShadowOffsetY = 3;
            this.btnDetainLicenses.Size = new System.Drawing.Size(349, 54);
            this.btnDetainLicenses.TabIndex = 9;
            this.btnDetainLicenses.Text = "Detain Licenses";
            this.btnDetainLicenses.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDetainLicenses.TextPaddingBottom = 0;
            this.btnDetainLicenses.TextPaddingLeft = 40;
            this.btnDetainLicenses.TextPaddingRight = 0;
            this.btnDetainLicenses.TextPaddingTop = 0;
            this.btnDetainLicenses.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnDetainLicenses.TextShadowOffsetX = 1;
            this.btnDetainLicenses.TextShadowOffsetY = 1;
            this.btnDetainLicenses.Click += new System.EventHandler(this.btnDetainLicenses_Click);
            // 
            // btnManageApplication
            // 
            this.btnManageApplication.BackColor = System.Drawing.Color.Transparent;
            this.btnManageApplication.BadgeBackColor = System.Drawing.Color.Red;
            this.btnManageApplication.BadgeForeColor = System.Drawing.Color.White;
            this.btnManageApplication.BadgeRadius = 8;
            this.btnManageApplication.BadgeRightMargin = 10;
            this.btnManageApplication.BadgeValue = 0;
            this.btnManageApplication.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(130)))), ((int)(((byte)(246)))));
            this.btnManageApplication.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnManageApplication.BorderColorStart = System.Drawing.Color.White;
            this.btnManageApplication.BorderRadiusBottomLeft = 20;
            this.btnManageApplication.BorderRadiusBottomRight = 20;
            this.btnManageApplication.BorderRadiusTopLeft = 20;
            this.btnManageApplication.BorderRadiusTopRight = 20;
            this.btnManageApplication.BorderThickness = 1;
            this.btnManageApplication.ButtonColorEnd = System.Drawing.Color.White;
            this.btnManageApplication.ButtonColorStart = System.Drawing.Color.White;
            this.btnManageApplication.ButtonImage = global::DVLD.Properties.Resources.Applications;
            this.btnManageApplication.CanBeep = false;
            this.btnManageApplication.CanShake = false;
            this.btnManageApplication.ClickSoundPath = null;
            this.btnManageApplication.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnManageApplication.DisabledOverlayOpacity = 0.5F;
            this.btnManageApplication.EnableBorderGradient = false;
            this.btnManageApplication.EnableClickSound = false;
            this.btnManageApplication.EnableFocusBorder = false;
            this.btnManageApplication.EnableHoverSound = false;
            this.btnManageApplication.EnablePressScale = false;
            this.btnManageApplication.EnableTextShadow = false;
            this.btnManageApplication.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnManageApplication.FocusBorderThickness = 2;
            this.btnManageApplication.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnManageApplication.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.btnManageApplication.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(246)))), ((int)(((byte)(255)))));
            this.btnManageApplication.HoverSoundPath = null;
            this.btnManageApplication.HoverTransitionSpeed = 0.08F;
            this.btnManageApplication.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManageApplication.ImageLeftMargin = 10;
            this.btnManageApplication.ImageRightMargin = 0;
            this.btnManageApplication.ImageSize = 35;
            this.btnManageApplication.IsReadOnly = false;
            this.btnManageApplication.Location = new System.Drawing.Point(520, 112);
            this.btnManageApplication.MakeRadial = false;
            this.btnManageApplication.Name = "btnManageApplication";
            this.btnManageApplication.PressAnimationSpeed = 0.2F;
            this.btnManageApplication.PressDepth = 1;
            this.btnManageApplication.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnManageApplication.RippleExpandSpeedFactor = 0.05F;
            this.btnManageApplication.RippleFadeSpeedFactor = 0.03F;
            this.btnManageApplication.ShadowBlurFactor = 0.85F;
            this.btnManageApplication.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnManageApplication.ShadowOffsetX = 3;
            this.btnManageApplication.ShadowOffsetY = 3;
            this.btnManageApplication.Size = new System.Drawing.Size(361, 54);
            this.btnManageApplication.TabIndex = 10;
            this.btnManageApplication.Text = "Manage Applications";
            this.btnManageApplication.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageApplication.TextPaddingBottom = 0;
            this.btnManageApplication.TextPaddingLeft = 40;
            this.btnManageApplication.TextPaddingRight = 0;
            this.btnManageApplication.TextPaddingTop = 0;
            this.btnManageApplication.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnManageApplication.TextShadowOffsetX = 1;
            this.btnManageApplication.TextShadowOffsetY = 1;
            this.btnManageApplication.Click += new System.EventHandler(this.btnManageApplication_Click);
            // 
            // btnDrivingLicenseService
            // 
            this.btnDrivingLicenseService.BackColor = System.Drawing.Color.Transparent;
            this.btnDrivingLicenseService.BadgeBackColor = System.Drawing.Color.Red;
            this.btnDrivingLicenseService.BadgeForeColor = System.Drawing.Color.White;
            this.btnDrivingLicenseService.BadgeRadius = 8;
            this.btnDrivingLicenseService.BadgeRightMargin = 10;
            this.btnDrivingLicenseService.BadgeValue = 0;
            this.btnDrivingLicenseService.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(130)))), ((int)(((byte)(246)))));
            this.btnDrivingLicenseService.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnDrivingLicenseService.BorderColorStart = System.Drawing.Color.White;
            this.btnDrivingLicenseService.BorderRadiusBottomLeft = 20;
            this.btnDrivingLicenseService.BorderRadiusBottomRight = 20;
            this.btnDrivingLicenseService.BorderRadiusTopLeft = 20;
            this.btnDrivingLicenseService.BorderRadiusTopRight = 20;
            this.btnDrivingLicenseService.BorderThickness = 1;
            this.btnDrivingLicenseService.ButtonColorEnd = System.Drawing.Color.White;
            this.btnDrivingLicenseService.ButtonColorStart = System.Drawing.Color.White;
            this.btnDrivingLicenseService.ButtonImage = global::DVLD.Properties.Resources.LocalDriving_License;
            this.btnDrivingLicenseService.CanBeep = false;
            this.btnDrivingLicenseService.CanShake = false;
            this.btnDrivingLicenseService.ClickSoundPath = null;
            this.btnDrivingLicenseService.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnDrivingLicenseService.DisabledOverlayOpacity = 0.5F;
            this.btnDrivingLicenseService.EnableBorderGradient = false;
            this.btnDrivingLicenseService.EnableClickSound = false;
            this.btnDrivingLicenseService.EnableFocusBorder = false;
            this.btnDrivingLicenseService.EnableHoverSound = false;
            this.btnDrivingLicenseService.EnablePressScale = false;
            this.btnDrivingLicenseService.EnableTextShadow = false;
            this.btnDrivingLicenseService.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnDrivingLicenseService.FocusBorderThickness = 2;
            this.btnDrivingLicenseService.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDrivingLicenseService.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(41)))), ((int)(((byte)(59)))));
            this.btnDrivingLicenseService.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(246)))), ((int)(((byte)(255)))));
            this.btnDrivingLicenseService.HoverSoundPath = null;
            this.btnDrivingLicenseService.HoverTransitionSpeed = 0.08F;
            this.btnDrivingLicenseService.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDrivingLicenseService.ImageLeftMargin = 10;
            this.btnDrivingLicenseService.ImageRightMargin = 0;
            this.btnDrivingLicenseService.ImageSize = 35;
            this.btnDrivingLicenseService.IsReadOnly = false;
            this.btnDrivingLicenseService.Location = new System.Drawing.Point(11, 112);
            this.btnDrivingLicenseService.MakeRadial = false;
            this.btnDrivingLicenseService.Name = "btnDrivingLicenseService";
            this.btnDrivingLicenseService.PressAnimationSpeed = 0.2F;
            this.btnDrivingLicenseService.PressDepth = 1;
            this.btnDrivingLicenseService.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnDrivingLicenseService.RippleExpandSpeedFactor = 0.05F;
            this.btnDrivingLicenseService.RippleFadeSpeedFactor = 0.03F;
            this.btnDrivingLicenseService.ShadowBlurFactor = 0.85F;
            this.btnDrivingLicenseService.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnDrivingLicenseService.ShadowOffsetX = 3;
            this.btnDrivingLicenseService.ShadowOffsetY = 3;
            this.btnDrivingLicenseService.Size = new System.Drawing.Size(349, 54);
            this.btnDrivingLicenseService.TabIndex = 11;
            this.btnDrivingLicenseService.Text = "Driving Licenses Services";
            this.btnDrivingLicenseService.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDrivingLicenseService.TextPaddingBottom = 0;
            this.btnDrivingLicenseService.TextPaddingLeft = 40;
            this.btnDrivingLicenseService.TextPaddingRight = 0;
            this.btnDrivingLicenseService.TextPaddingTop = 0;
            this.btnDrivingLicenseService.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnDrivingLicenseService.TextShadowOffsetX = 1;
            this.btnDrivingLicenseService.TextShadowOffsetY = 1;
            this.btnDrivingLicenseService.Click += new System.EventHandler(this.btnDrivingLicenseService_Click);
            // 
            // btnClose
            // 
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.BadgeBackColor = System.Drawing.Color.Red;
            this.btnClose.BadgeForeColor = System.Drawing.Color.White;
            this.btnClose.BadgeRadius = 8;
            this.btnClose.BadgeRightMargin = 10;
            this.btnClose.BadgeValue = 0;
            this.btnClose.BorderColor = System.Drawing.Color.MediumSlateBlue;
            this.btnClose.BorderColorEnd = System.Drawing.Color.Gray;
            this.btnClose.BorderColorStart = System.Drawing.Color.White;
            this.btnClose.BorderRadiusBottomLeft = 10;
            this.btnClose.BorderRadiusBottomRight = 10;
            this.btnClose.BorderRadiusTopLeft = 10;
            this.btnClose.BorderRadiusTopRight = 10;
            this.btnClose.BorderThickness = 1;
            this.btnClose.ButtonColorEnd = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(245)))), ((int)(((byte)(249)))));
            this.btnClose.ButtonColorStart = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(245)))), ((int)(((byte)(249)))));
            this.btnClose.ButtonImage = global::DVLD.Properties.Resources.Close_32;
            this.btnClose.CanBeep = false;
            this.btnClose.CanShake = false;
            this.btnClose.ClickSoundPath = null;
            this.btnClose.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnClose.DisabledOverlayOpacity = 0.5F;
            this.btnClose.EnableBorderGradient = false;
            this.btnClose.EnableClickSound = false;
            this.btnClose.EnableFocusBorder = false;
            this.btnClose.EnableHoverSound = false;
            this.btnClose.EnablePressScale = false;
            this.btnClose.EnableTextShadow = false;
            this.btnClose.FocusBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnClose.FocusBorderThickness = 2;
            this.btnClose.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClose.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(85)))), ((int)(((byte)(105)))));
            this.btnClose.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(232)))), ((int)(((byte)(240)))));
            this.btnClose.HoverSoundPath = null;
            this.btnClose.HoverTransitionSpeed = 0.08F;
            this.btnClose.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.ImageLeftMargin = 0;
            this.btnClose.ImageRightMargin = 3;
            this.btnClose.ImageSize = 25;
            this.btnClose.IsReadOnly = false;
            this.btnClose.Location = new System.Drawing.Point(1413, 795);
            this.btnClose.MakeRadial = false;
            this.btnClose.Margin = new System.Windows.Forms.Padding(0);
            this.btnClose.Name = "btnClose";
            this.btnClose.PressAnimationSpeed = 0.2F;
            this.btnClose.PressDepth = 1;
            this.btnClose.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnClose.RippleExpandSpeedFactor = 0.05F;
            this.btnClose.RippleFadeSpeedFactor = 0.03F;
            this.btnClose.ShadowBlurFactor = 0.85F;
            this.btnClose.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnClose.ShadowOffsetX = 3;
            this.btnClose.ShadowOffsetY = 3;
            this.btnClose.Size = new System.Drawing.Size(118, 41);
            this.btnClose.TabIndex = 57;
            this.btnClose.Text = "Close";
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.TextPaddingBottom = 0;
            this.btnClose.TextPaddingLeft = 15;
            this.btnClose.TextPaddingRight = 0;
            this.btnClose.TextPaddingTop = 0;
            this.btnClose.TextShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnClose.TextShadowOffsetX = 1;
            this.btnClose.TextShadowOffsetY = 1;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1540, 845);
            this.ControlBox = false;
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.gbApplication);
            this.Controls.Add(this.gbAccountSettings);
            this.Controls.Add(this.btnClose1);
            this.Controls.Add(this.pnSideBar);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "DVLD";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.pnSideBar.ResumeLayout(false);
            this.gbAccountSettings.ResumeLayout(false);
            this.gbApplication.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private SiticoneNetFrameworkUI.SiticonePanel pnSideBar;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnPeople;
        private SiticoneNetFrameworkUI.SiticoneCloseButton btnClose1;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnUsers;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnAccountSettings;
        private SiticoneNetFrameworkUI.SiticoneAuraGroupBox gbAccountSettings;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnCurrentUserInfo;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnChangePassword;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnSignOut;
        private SiticoneNetFrameworkUI.SiticoneAuraGroupBox gbApplication;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnManageApplicationTypes;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnManageTestTypes;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnDetainLicenses;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnManageApplication;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnDrivingLicenseService;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnApplications;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnDrivers;
        private SiticoneNetFrameworkUI.SiticoneButtonAdvanced btnClose;
    }
}